### ISSUE TITLE
ValueError: expected sequence of length 3 at dim 2 (got 0)

### ISSUE THREAD

**Issue by Yang1231** [boyu-ai/Hands-on-RL#31]
How to deal this? In SAC training.

**Comment by zxe001** [comment]
+1,py3.7 could run

**Comment by COCOHUHU** [comment]
I have this problem as well... appreciate if someone can provide a solution

**Comment by zxe001** [comment]
Resolved

**Comment by zhyantao** [comment]
Maybe https://github.com/boyu-ai/Hands-on-RL/issues/30 is useful for you.

**Comment by wallyxjh** [comment]
How Resolved this problem

**Comment by wallyxjh** [comment]
Traceback (most recent call last):
  File "/Users/james/workspace/school/python/demo/DDPG.py", line 113, in <module>
    return_list = rl_utils.train_off_policy_agent(env, agent, num_episodes, replay_buffer, minimal_size, batch_size)
  File "/Users/james/workspace/school/python/demo/rl_utils.py", line 65, in train_off_policy_agent
    action = agent.take_action(state)
  File "/Users/james/workspace/school/python/demo/DDPG.py", line 57, in take_action
    state = torch.tensor([state], dtype=torch.float).to(self.device)
ValueError: expected sequence of length 3 at dim 2 (got 0)

**Comment by dawoshi** [comment]
gym版本问题
state = env.reset() 
state, _ = env.reset()

next_state, reward, done, _= env.step(action)
next_state, reward, done, _, _= env.step(action)
